In [14]:
import pyomo.environ as pyo
from pyomo.environ import *
from pyomo.opt import SolverFactory
from math import radians
import numpy as np 
import ast

model = ConcreteModel()

k=np.array([[8,7,8,9],
[10,10,9,10],
[7,6,5,6],
[4,2,-1,1],
[0,0,7,9],
[6,5,4,3]])
print(k)
K='{'
for i in range(len(k)):
    for j in range(len(k[i])):
        K+=f'({i},{j}):{k[i][j]},'
K+='}'
k = ast.literal_eval(K)
print(k)

model.V = Set(initialize=[0,1,2,3,4,5], doc='ensemble des vols')
model.H = Set(initialize=[0,1,2,3], doc='ensemble des tranches dheures')

# %%
model.v = Param(initialize=6, doc='le nombre de vols')
model.h = Param(initialize=4, doc='le nombre des tranches dheures')

model.x = Var(model.V, model.H,domain=Binary, doc='Variable de décision')


model.p = Param(model.V,model.H ,initialize=k,doc='les profits de chaque vol i au tranche dheure j ')

def Contraint1(model,j):
  return sum(model.x[i,j] for i in model.V)<= 2

model.C1 = Constraint (model.H, rule=Contraint1, doc='c1')

def Contraint2(model,i):
  return sum(model.x[i,j] for j in model.H)== 1

model.C2 = Constraint (model.V, rule=Contraint2, doc='c2')

def Contraint3(model):
  return model.x[4,0] + model.x[4,1]== 0

model.C3 = Constraint (rule=Contraint3, doc='c3')


def objective_rule(model):
  return sum(model.p[i,j]* model.x[i,j] for i in model.V for j in model.H)
model.objective = Objective(rule=objective_rule, sense=maximize, doc='Define objective function')

opt = SolverFactory('gurobi')
results = opt.solve(model,tee=True)

opt.solve(model)
model.display()


[[ 8  7  8  9]
 [10 10  9 10]
 [ 7  6  5  6]
 [ 4  2 -1  1]
 [ 0  0  7  9]
 [ 6  5  4  3]]
{(0, 0): 8, (0, 1): 7, (0, 2): 8, (0, 3): 9, (1, 0): 10, (1, 1): 10, (1, 2): 9, (1, 3): 10, (2, 0): 7, (2, 1): 6, (2, 2): 5, (2, 3): 6, (3, 0): 4, (3, 1): 2, (3, 2): -1, (3, 3): 1, (4, 0): 0, (4, 1): 0, (4, 2): 7, (4, 3): 9, (5, 0): 6, (5, 1): 5, (5, 2): 4, (5, 3): 3}


C:\Users\pc\AppData\Local\Temp/ipykernel_2072/3660358374.py:38: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return sum(model.x[i,j] for i in model.V)<= 2
C:\Users\pc\AppData\Local\Temp/ipykernel_2072/3660358374.py:43: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return sum(model.x[i,j] for j in model.H)== 1
C:\Users\pc\AppData\Local\Temp/ipykernel_2072/3660358374.py:54: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return sum(model.p[i,j]* model.x[i,j] for i in model.V for j in model.H)


Set parameter Username
Academic license - for non-commercial use only - expires 2022-07-10
Read LP format model from file C:\Users\pc\AppData\Local\Temp\tmpz2h758cq.pyomo.lp
Reading time = 0.01 seconds
x25: 12 rows, 25 columns, 51 nonzeros
Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 12 rows, 25 columns and 51 nonzeros
Model fingerprint: 0x150a1b9d
Variable types: 1 continuous, 24 integer (24 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 2e+00]
Found heuristic solution: objective 42.0000000
Presolve removed 3 rows and 4 columns
Presolve time: 0.00s
Presolved: 9 rows, 21 columns, 42 nonzeros
Variable types: 0 continuous, 21 integer (21 binary)
Found heuristic solution: objective 43.0000000

Root relaxation: objective 4.400000e+01, 12 iterations, 0.00 seconds (0.00 w

[[ 8  7  8  9]
 [10 10  9 10]
 [ 7  6  5  6]
 [ 4  2 -1  1]
 [ 0  0  7  9]
 [ 6  5  4  3]]
{(0, 0): 8, (0, 1): 7, (0, 2): 8, (0, 3): 9, (1, 0): 10, (1, 1): 10, (1, 2): 9, (1, 3): 10, (2, 0): 7, (2, 1): 6, (2, 2): 5, (2, 3): 6, (3, 0): 4, (3, 1): 2, (3, 2): -1, (3, 3): 1, (4, 0): 0, (4, 1): 0, (4, 2): 7, (4, 3): 9, (5, 0): 6, (5, 1): 5, (5, 2): 4, (5, 3): 3}


In [7]:
from numpy import *
n=11
m=2
c=[70,70]
q= [0,2.0, 12.0, 14.0, 2.0, 17.0, 20.0, 2.0, 26.0, 7.0, 6.0]
d= [[0.0, 11.40175425099138, 57.56735185849702, 27.65863337187866, 22.20360331117452, 31.144823004794873, 33.37663853655727, 40.22437072223753, 33.1058907144937, 35.11409973215888, 47.20169488482379],
    [11.40175425099138, 0.0, 46.17358552246078, 35.34119409414458, 12.206555615733702, 37.73592452822641, 36.49657518178932, 32.31098884280702, 25.495097567963924, 30.01666203960727, 41.10960958218893],
    [57.56735185849702, 46.17358552246078, 0.0, 76.00657866263946, 37.21558813185679, 76.23647421018367, 70.71067811865476, 35.77708763999664, 39.824615503479755, 45.880278987817846, 48.104053883222775],
    [27.65863337187866, 35.34119409414458, 76.00657866263946, 0.0, 39.319206502675, 5.0, 57.245087125446844, 46.486557196677836, 60.207972893961475, 36.24913792078372, 74.81310045707235],
    [22.20360331117452, 12.206555615733702, 37.21558813185679, 39.319206502675, 0.0, 40.26164427839479, 47.80167361086848, 20.615528128088304, 29.546573405388315, 20.8806130178211, 45.617978911828175],
    [31.144823004794873, 37.73592452822641, 76.23647421018367, 5.0, 40.26164427839479, 0.0, 61.741396161732524, 45.12205669071391, 63.00793600809346, 34.48187929913333, 77.98717843338096],
    [33.37663853655727, 36.49657518178932, 70.71067811865476, 57.245087125446844, 47.80167361086848, 61.741396161732524, 0.0, 68.41052550594829, 31.400636936215164, 66.37017402418047, 33.37663853655727], 
    [40.22437072223753, 32.31098884280702, 35.77708763999664, 46.486557196677836, 20.615528128088304, 45.12205669071391, 68.41052550594829, 0.0, 47.51841748206689, 11.0, 62.81719509815764], [33.1058907144937, 25.495097567963924, 39.824615503479755, 60.207972893961475, 29.546573405388315, 63.00793600809346, 31.400636936215164, 47.51841748206689, 0.0, 50.32891812864648, 16.1245154965971], [35.11409973215888, 30.01666203960727, 45.880278987817846, 36.24913792078372, 20.8806130178211, 34.48187929913333, 66.37017402418047, 11.0, 50.32891812864648, 0.0, 66.30987860040162], [47.20169488482379, 41.10960958218893, 48.104053883222775, 74.81310045707235, 45.617978911828175, 77.98717843338096, 33.37663853655727, 62.81719509815764, 16.1245154965971, 66.30987860040162, 0.0]]
K='{'
for i in range(len(d)):
    for j in range(len(d[i])):
        K+=f'({i},{j}):{d[i][j]},'
K+='}'
d = ast.literal_eval(K)
print(k)
print(d)

{(0, 0): 8, (0, 1): 7, (0, 2): 8, (0, 3): 9, (1, 0): 10, (1, 1): 10, (1, 2): 9, (1, 3): 10, (2, 0): 7, (2, 1): 6, (2, 2): 5, (2, 3): 6, (3, 0): 4, (3, 1): 2, (3, 2): -1, (3, 3): 1, (4, 0): 0, (4, 1): 0, (4, 2): 7, (4, 3): 9, (5, 0): 6, (5, 1): 5, (5, 2): 4, (5, 3): 3}
{(0, 0): 0.0, (0, 1): 11.40175425099138, (0, 2): 57.56735185849702, (0, 3): 27.65863337187866, (0, 4): 22.20360331117452, (0, 5): 31.144823004794873, (0, 6): 33.37663853655727, (0, 7): 40.22437072223753, (0, 8): 33.1058907144937, (0, 9): 35.11409973215888, (0, 10): 47.20169488482379, (1, 0): 11.40175425099138, (1, 1): 0.0, (1, 2): 46.17358552246078, (1, 3): 35.34119409414458, (1, 4): 12.206555615733702, (1, 5): 37.73592452822641, (1, 6): 36.49657518178932, (1, 7): 32.31098884280702, (1, 8): 25.495097567963924, (1, 9): 30.01666203960727, (1, 10): 41.10960958218893, (2, 0): 57.56735185849702, (2, 1): 46.17358552246078, (2, 2): 0.0, (2, 3): 76.00657866263946, (2, 4): 37.21558813185679, (2, 5): 76.23647421018367, (2, 6): 70.7

In [8]:
# %%
# Import of the pyomo module
from pyomo.environ import *
from pyomo.opt import SolverFactory
import pyomo.environ

# Creation of a Concrete Model
model = ConcreteModel()

# %%
model.K = Set(initialize=range(m), doc='interval de lindice k')

model.I = Set(initialize=range(0,n), doc='interval de lindice i et J')
model.J = Set(initialize=range(1,n), doc='Quantity conducteur')
# %%

model.c = Param(model.K,initialize= c, doc='capacite de chaque véhicule')
model.q = Param(model.I,initialize= q, doc='quantite du conteneur i')
model.d = Param(model.I,model.I,initialize=d, domain= Any ,doc=' distance entre le point i et j')
# %%
model.x = Var(model.I, model.I,model.K,domain=Binary, doc='variable de decision boolean prend 1 si le vehicule 0 parcourt l arrete (i,j)')
model.y = Var(model.I,model.K,bounds=(0,None),domain=Integers, doc='ordre de passage')

# %%
def Cotraint1(model,j):
  return sum(model.x[i,j,k] for i in [l for l in model.I if l != j] for k in model.K)==1
model.C1 = Constraint(model.J, rule=Cotraint1, doc='Chaque vehicule si utiliser demarre du depot')


def Contraint2(model,k):
  return sum(model.x[0,j,k] for j in model.J)==1

model.C2 = Constraint ( model.K, rule=Contraint2, doc='verification de non chevauchement ')

def Contraint3(model,j,k):
  return sum(model.x[i,j,k] for i in [l for l in model.I if l != j] )==sum(model.x[j,i,k] for i in [l for l in model.I if l != j])

model.C3 = Constraint (model.J,model.K, rule=Contraint3, doc='  Chaque point visite doit etre quitter.')

def Contraint4(model,k):
  return  sum((model.x[i,j,k]*q[j]) for i in model.I for j in [l for l in model.J if l != i])<=model.c[k]

model.C4 = Constraint (model.K, rule=Contraint4, doc='La capacite de chaque vehicule doit etre respecter.')

def Contraint5(model,i,j ,k):
  return (model.y[i,k]+1)<=(model.y[j,k]+n*(1-model.x[i,j,k])) 
model.C5 = Constraint(model.I,model.J,model.K, rule=Contraint5, doc='verification daffectation de terminal')

# %%

# %%
def objective_rule(model):
  return sum(model.x[i,j,k]*model.d[i,j] for i in model.I for j in [l for l in model.I if l != i] for k in model.K)
model.objective = Objective(rule=objective_rule, sense=minimize, doc='Define objective function')

# %%
def pyomo_postprocess(options=None, instance=None, results=None):
  model.x.display()
# %%


opt = SolverFactory("gurobi")
results = opt.solve(model,tee=True)
#sends results to stdout
results.write()
print("\nDisplaying Solution\n" + '-'*60)
pyomo_postprocess(None, model, results)
# %%

C:\Users\pc\AppData\Local\Temp/ipykernel_2072/538639296.py:26: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return sum(model.x[i,j,k] for i in [l for l in model.I if l != j] for k in model.K)==1
C:\Users\pc\AppData\Local\Temp/ipykernel_2072/538639296.py:31: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return sum(model.x[0,j,k] for j in model.J)==1
C:\Users\pc\AppData\Local\Temp/ipykernel_2072/538639296.py:36: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return sum(model.x[i,j,k] for i in [l for l in model.I if l != j] )==sum(model.x[j,i,k] for i in [l for l in model.I if l != j])
C:\Us

Set parameter Username
Academic license - for non-commercial use only - expires 2022-07-10
Read LP format model from file C:\Users\pc\AppData\Local\Temp\tmpdxpkbgw9.pyomo.lp
Reading time = 0.01 seconds
x265: 255 rows, 263 columns, 1441 nonzeros
Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 255 rows, 263 columns and 1441 nonzeros
Model fingerprint: 0xc4fb8069
Variable types: 1 continuous, 262 integer (240 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+01]
  Objective range  [5e+00, 8e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 7e+01]
Found heuristic solution: objective 587.6139449
Presolve removed 21 rows and 23 columns
Presolve time: 0.01s
Presolved: 234 rows, 240 columns, 1394 nonzeros
Variable types: 0 continuous, 240 integer (220 binary)

Root relaxation: objective 2.282370e+02, 53 iterations, 0.00 seconds (0.00 work units)

    Nodes    |