In [32]:
from collections import deque
import numpy as np
import pandas as pd

import datetime as dt
from datetime import datetime, timedelta
import time
import math

Imprting Data from excel File using pandas lib

In [33]:
Data = pd.read_excel('Vol.xlsx', sheet_name='Vol')
Data.info

<bound method DataFrame.info of           Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
0   2022-04-09       NaN  07:15:00  DAH   4000    TUN  7TVKD     B738   P18   
1   2022-04-09       NaN  07:30:00  DTH   1400    RNS  7TVCL     DH8D   PA1   
2   2022-04-09       NaN  07:30:00  DTH   1408    RNS  7TVCR     DH8D   PA1   
3   2022-04-09       NaN  08:00:00  DAH   6258    CZL  7TVUK    ATR72   PA1   
4   2022-04-09       NaN  08:00:00  DTH   2320    AZR  7TVCE     B738   PA1   
..         ...       ...       ...  ...    ...    ...    ...      ...   ...   
189 2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   
190 2022-04-10  19:55:00       NaN  DAH   1041  7TVKK   B738      NCE   P19   
191 2022-04-10  20:30:00       NaN  DAH   4003  7TVKM   B738      TUN   P15   
192 2022-04-10       NaN  22:45:00  DAH   4062  7TVJA   A330      DXB   P21   
193 2022-04-10  22:50:00       NaN  AZA    802    NaN   A320      FCO   P16   

          Remarque 

In [34]:
Data.head

<bound method NDFrame.head of           Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
0   2022-04-09       NaN  07:15:00  DAH   4000    TUN  7TVKD     B738   P18   
1   2022-04-09       NaN  07:30:00  DTH   1400    RNS  7TVCL     DH8D   PA1   
2   2022-04-09       NaN  07:30:00  DTH   1408    RNS  7TVCR     DH8D   PA1   
3   2022-04-09       NaN  08:00:00  DAH   6258    CZL  7TVUK    ATR72   PA1   
4   2022-04-09       NaN  08:00:00  DTH   2320    AZR  7TVCE     B738   PA1   
..         ...       ...       ...  ...    ...    ...    ...      ...   ...   
189 2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   
190 2022-04-10  19:55:00       NaN  DAH   1041  7TVKK   B738      NCE   P19   
191 2022-04-10  20:30:00       NaN  DAH   4003  7TVKM   B738      TUN   P15   
192 2022-04-10       NaN  22:45:00  DAH   4062  7TVJA   A330      DXB   P21   
193 2022-04-10  22:50:00       NaN  AZA    802    NaN   A320      FCO   P16   

          Remarque   

In [35]:
Data.shape
Data= Data.astype({"Date": str}, errors='raise')

We needed to make the data col as string because pands automaticly detaxted dates , but it made it deficult for us to process 

In [36]:
Data.info()
print(Data['Date'])


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Date      194 non-null    object
 1   HPA       95 non-null     object
 2   HPD       99 non-null     object
 3   Cie       194 non-null    object
 4   Ligne     194 non-null    int64 
 5   Esc 1     172 non-null    object
 6   Immat     180 non-null    object
 7   Type app  194 non-null    object
 8   PKG       194 non-null    object
 9   Remarque  194 non-null    object
 10  Comment   170 non-null    object
 11  Terminal  194 non-null    object
dtypes: int64(1), object(11)
memory usage: 18.3+ KB
0      2022-04-09
1      2022-04-09
2      2022-04-09
3      2022-04-09
4      2022-04-09
          ...    
189    2022-04-10
190    2022-04-10
191    2022-04-10
192    2022-04-10
193    2022-04-10
Name: Date, Length: 194, dtype: object


In [37]:

Time=[]
for i in range (len(Data)):
    if pd.notna(Data['HPA'][i]) : #Convert heure prevu d'accostage and adding to her the exact date
        Time.append(str(Data["Date"][i])+" "+str(Data['HPA'][i]))
    elif pd.notna(Data['HPD'][i]) :#Convert heure prevu d'essacostage and adding to her the exact date
        Time.append(str(Data["Date"][i])+" "+str(Data['HPD'][i]))
    else:
        Time.append(float('nan'))

print(Time)
Data['DATETIME']=Time #creating a new col in the table with the datetime for the operation .
print(Data)

['2022-04-09 07:15:00', '2022-04-09 07:30:00', '2022-04-09 07:30:00', '2022-04-09 08:00:00', '2022-04-09 08:00:00', '2022-04-09 08:15:00', '2022-04-09 08:45:00', '2022-04-09 08:45:00', '2022-04-09 08:50:00', '2022-04-09 09:00:00', '2022-04-09 09:10:00', '2022-04-09 09:10:00', '2022-04-09 09:10:00', '2022-04-09 09:10:00', '2022-04-09 09:15:00', '2022-04-09 09:15:00', '2022-04-09 09:15:00', '2022-04-09 09:20:00', '2022-04-09 09:45:00', '2022-04-09 09:45:00', '2022-04-09 10:00:00', '2022-04-09 10:00:00', '2022-04-09 10:00:00', '2022-04-09 10:10:00', '2022-04-09 10:15:00', '2022-04-09 10:20:00', '2022-04-09 10:20:00', '2022-04-09 10:25:00', '2022-04-09 10:30:00', '2022-04-09 10:30:00', '2022-04-09 10:30:00', '2022-04-09 10:35:00', '2022-04-09 10:50:00', '2022-04-09 10:50:00', '2022-04-09 11:00:00', '2022-04-09 11:00:00', '2022-04-09 11:05:00', '2022-04-09 11:20:00', '2022-04-09 11:35:00', '2022-04-09 11:45:00', '2022-04-09 11:45:00', '2022-04-09 12:00:00', '2022-04-09 12:05:00', '2022-04-0

In [38]:

TimeGap=input('Give a Time GAP equal or bigger to 6  :') #input gap time based on the need and calculation 
TimeGap=int(TimeGap)
def Trans_to_min(x):
    D=x.day*24*60
    min = x.minute
    H = x.hour *60
    return int(D+min+H)
# this fenction transfer the date time into a number , we transfered the date into munites also , because in the night shift , the 00:00 comes after 23:00 , so we needed another variable to tell us that the day changed

Graph_intervale=[]

for i in range(len(Data)):
    try:
        Graph_intervale.append([])
        Time[i] = dt.datetime.strptime(str(Time[i]), '%Y-%d-%m %H:%M:%S')
        min= Time[i]- dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(min))
        max= Time[i]+ dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(max))
    except:
        Time[i] = dt.datetime.strptime(str(Time[i]), '%d-%m-%Y %H:%M:%S')
        min= Time[i]- dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(min))
        max= Time[i]+ dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(max)) 
print((Graph_intervale))
Data['Graph_intervale']=Graph_intervale


[[6194, 6196], [6209, 6211], [6209, 6211], [6239, 6241], [6239, 6241], [6254, 6256], [6284, 6286], [6284, 6286], [6289, 6291], [6299, 6301], [6309, 6311], [6309, 6311], [6309, 6311], [6309, 6311], [6314, 6316], [6314, 6316], [6314, 6316], [6319, 6321], [6344, 6346], [6344, 6346], [6359, 6361], [6359, 6361], [6359, 6361], [6369, 6371], [6374, 6376], [6379, 6381], [6379, 6381], [6384, 6386], [6389, 6391], [6389, 6391], [6389, 6391], [6394, 6396], [6409, 6411], [6409, 6411], [6419, 6421], [6419, 6421], [6424, 6426], [6439, 6441], [6454, 6456], [6464, 6466], [6464, 6466], [6479, 6481], [6484, 6486], [6504, 6506], [6509, 6511], [6509, 6511], [6539, 6541], [6544, 6546], [6549, 6551], [6554, 6556], [6559, 6561], [6559, 6561], [6564, 6566], [6574, 6576], [6619, 6621], [6629, 6631], [6629, 6631], [6629, 6631], [6629, 6631], [6634, 6636], [6659, 6661], [6669, 6671], [6674, 6676], [6674, 6676], [6679, 6681], [6679, 6681], [6684, 6686], [6694, 6696], [6709, 6711], [6719, 6721], [6719, 6721], [6719

we transftered into munites every variables for us to create an interval of time .

In [39]:
Brigade=[]
for i in range (len(Data)):
    if (Time[i].hour >=0 and Time[i].hour<=7) or (Time[i].hour >=19 and Time[i].hour<=23): 
        Brigade.append("Nuit")
    else:
        Brigade.append("Journee")
Data['Brigade']=Brigade
print(Data)

           Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
0    2022-04-09       NaN  07:15:00  DAH   4000    TUN  7TVKD     B738   P18   
1    2022-04-09       NaN  07:30:00  DTH   1400    RNS  7TVCL     DH8D   PA1   
2    2022-04-09       NaN  07:30:00  DTH   1408    RNS  7TVCR     DH8D   PA1   
3    2022-04-09       NaN  08:00:00  DAH   6258    CZL  7TVUK    ATR72   PA1   
4    2022-04-09       NaN  08:00:00  DTH   2320    AZR  7TVCE     B738   PA1   
..          ...       ...       ...  ...    ...    ...    ...      ...   ...   
189  2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   
190  2022-04-10  19:55:00       NaN  DAH   1041  7TVKK   B738      NCE   P19   
191  2022-04-10  20:30:00       NaN  DAH   4003  7TVKM   B738      TUN   P15   
192  2022-04-10       NaN  22:45:00  DAH   4062  7TVJA   A330      DXB   P21   
193  2022-04-10  22:50:00       NaN  AZA    802    NaN   A320      FCO   P16   

          Remarque                 Comm

In [40]:
#Select Brigate
Date=input('Input your the date you want')
Brigade=input('Input the brigade you want ')

In [41]:

if Brigade=='Journee':
    Selected_Data=Data.loc[(Data['Date'] == Date) & (Data['Brigade'] == Brigade) ]
if Brigade=='Nuit':
    Time01 = dt.datetime.strptime(str(Date)+" 19:00:00", '%Y-%m-%d %H:%M:%S')
    Time02 = dt.datetime.strptime(str(Date)+" 08:00:00", '%Y-%m-%d %H:%M:%S')

    Time01=Trans_to_min(Time01)
    Time02=Trans_to_min(Time02) + 24*60
    print(Time01)
    print(Time02)
    Selected=[]
    for i in range(len(Data)):
        Time = dt.datetime.strptime(Data['DATETIME'][i], '%Y-%m-%d %H:%M:%S')
        Time=Trans_to_min(Time)
        if Time >= Time01 and Time < Time02 :
            Selected.append(Data['DATETIME'][i])
    Selected_Data = Data.loc[Data['DATETIME'].isin(Selected)]

print(Selected_Data)


          Date       HPA       HPD  Cie  Ligne Esc 1  Immat Type app   PKG  \
3   2022-04-09       NaN  08:00:00  DAH   6258   CZL  7TVUK    ATR72   PA1   
4   2022-04-09       NaN  08:00:00  DTH   2320   AZR  7TVCE     B738   PA1   
5   2022-04-09       NaN  08:15:00  DAH   6170   AAE  7TVUM    ATR72   PA1   
6   2022-04-09       NaN  08:45:00  DAH   6180   ORN  7TVUT    ATR72   PA1   
7   2022-04-09       NaN  08:45:00  DTH   1154   HME  7TVCD     B738  P10C   
..         ...       ...       ...  ...    ...   ...    ...      ...   ...   
91  2022-04-09  18:20:00       NaN  DAH   3017   IST  7TVKO     B738   P15   
92  2022-04-09       NaN  18:20:00  DAH   6026   CZL  7TVJU     B736  P11A   
93  2022-04-09       NaN  18:30:00  DAH   6106   ORN  7TVJS     B736    P9   
94  2022-04-09  18:40:00       NaN  DAH   6193   CZL  7TVKE     B738   P12   
95  2022-04-09       NaN  18:40:00  DAH   6006   AAE  7TVKL     B738  P10C   

         Remarque                  Comment Terminal            

Slection of the brigade based on the need , the pd.loc will filter based on the condition ,but the indexes will stay the same.

In [42]:
Graph_intervale=Selected_Data["Graph_intervale"]
Graph_intervale=np.array(Graph_intervale) #doing array to remove the indexes from the selections before , also sice we require a type list for our code to work 
print(Graph_intervale)

Graph01=Selected_Data.loc[Selected_Data['Terminal'] == 'T1']
Graph01=np.array(Graph01["Graph_intervale"])
Graph02=Selected_Data.loc[Selected_Data['Terminal'] == 'T2']
Graph02=np.array(Graph02["Graph_intervale"])
Graph03=Selected_Data.loc[Selected_Data['Terminal'] == 'T4']
Graph03=np.array(Graph03["Graph_intervale"])

[list([6239, 6241]) list([6239, 6241]) list([6254, 6256])
 list([6284, 6286]) list([6284, 6286]) list([6289, 6291])
 list([6299, 6301]) list([6309, 6311]) list([6309, 6311])
 list([6309, 6311]) list([6309, 6311]) list([6314, 6316])
 list([6314, 6316]) list([6314, 6316]) list([6319, 6321])
 list([6344, 6346]) list([6344, 6346]) list([6359, 6361])
 list([6359, 6361]) list([6359, 6361]) list([6369, 6371])
 list([6374, 6376]) list([6379, 6381]) list([6379, 6381])
 list([6384, 6386]) list([6389, 6391]) list([6389, 6391])
 list([6389, 6391]) list([6394, 6396]) list([6409, 6411])
 list([6409, 6411]) list([6419, 6421]) list([6419, 6421])
 list([6424, 6426]) list([6439, 6441]) list([6454, 6456])
 list([6464, 6466]) list([6464, 6466]) list([6479, 6481])
 list([6484, 6486]) list([6504, 6506]) list([6509, 6511])
 list([6509, 6511]) list([6539, 6541]) list([6544, 6546])
 list([6549, 6551]) list([6554, 6556]) list([6559, 6561])
 list([6559, 6561]) list([6564, 6566]) list([6574, 6576])
 list([6619, 6

In [43]:
def Verify_in_interval(M1,M2):
    if M1[0]<=M2[0] and M1[1]>=M2[0]:
        return True
    elif M1[0]<=M2[1] and M1[1]>=M2[1]:
        return True
    else: 
        return False 
def   listAdj(M):
    listAdj=[]
    for i in range(len(M)):
        listAdj.append([])
        for j in [x for x in range(len(M)) if x != i]:
            if Verify_in_interval(M[i],M[j]) or Verify_in_interval(M[j],M[i]) :
                listAdj[i].append(j)
            else:
                pass
    return listAdj
            #print(listAdj[i])
    #print(listAdj[i])
# print(M)
Adj=listAdj(Graph_intervale)
print(Adj)

Adj01=listAdj(Graph01)
Adj02=listAdj(Graph02)
Adj03=listAdj(Graph03)

[[1], [0], [], [4], [3], [], [], [8, 9, 10], [7, 9, 10], [7, 8, 10], [7, 8, 9], [12, 13], [11, 13], [11, 12], [], [16], [15], [18, 19], [17, 19], [17, 18], [], [], [23], [22], [], [26, 27], [25, 27], [25, 26], [], [30], [29], [32], [31], [], [], [], [37], [36], [], [], [], [42], [41], [], [], [], [], [48], [47], [], [], [], [53, 54, 55], [52, 54, 55], [52, 53, 55], [52, 53, 54], [], [], [], [60], [59], [62], [61], [], [], [], [67, 68], [66, 68], [66, 67], [], [], [72], [71], [74], [73], [76], [75], [], [], [], [], [], [83], [82], [], [86], [85], [], [89], [88], [], [92], [91]]


In [44]:
def matriceAdj(Adj):
    Mat=[]
    for i in range( len(Adj)):
        Mat.append([])
        for j in range( len(Adj)):
            Mat[i].append(0)
            for k in range(len(Adj[i])):
                if j==Adj[i][k]:
                    Mat[i][j]=1
    return Mat

In [45]:
def arret(M):
    ex=[[],[]]
    for i in range (len(M)-1):
        for j in range(i+1,len(M)):
            if M[i][j]==1:
                ex[0].append(i)
                ex[1].append(j)
    return ex
#Create a list of start and end of each arret in our graph

In [46]:
Mat=matriceAdj(Adj)
Mat= np.array(Mat)
print (Mat)

[[0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]]


In [47]:
Ex=arret(Mat)
print("ex1= ",Ex[0])
print("ex2= ",Ex[1])


print(len(Ex[0]))

ex1=  [0, 3, 7, 7, 7, 8, 8, 9, 11, 11, 12, 15, 17, 17, 18, 22, 25, 25, 26, 29, 31, 36, 41, 47, 52, 52, 52, 53, 53, 54, 59, 61, 66, 66, 67, 71, 73, 75, 82, 85, 88, 91]
ex2=  [1, 4, 8, 9, 10, 9, 10, 10, 12, 13, 13, 16, 18, 19, 19, 23, 26, 27, 27, 30, 32, 37, 42, 48, 53, 54, 55, 54, 55, 55, 60, 62, 67, 68, 68, 72, 74, 76, 83, 86, 89, 92]
42


In [49]:
def Gloton(Adj):
    n=len(Adj)
    NC=dict()
    C=[0 for k in range(n)]
    for i in range(n):
        NC[i]=[]
    def  rajouter(k,NC):
        if ((k in NC)==True):
            return NC
        else:
            NC.append(k)
            return NC
    i=0
    while i<=n-1:
        exist=True
        k=0
        while (exist==True):
            exist=k in NC[i]
            if (exist==True):
                k+=1
        C[i]=k    
        for j in range(len(Adj[i])):
            voisin=Adj[i][j]
            NC[voisin]=rajouter(k,NC[voisin])
        i+=1
    return C
# C=Gloton(Adj)
C1=Gloton(Adj01)
C2=Gloton(Adj02)
C3=Gloton(Adj03)
def Minimum(C):
    min_Conducteur=0
    for i in C:
        if min_Conducteur<=i:
            min_Conducteur=i
    min_Conducteur+=1
    return min_Conducteur

min_Conducteur=(Minimum(C1)+Minimum(C2)+Minimum(C3))

print(min_Conducteur)
Conducteur=0
while (Conducteur<min_Conducteur):
    Conducteur=input('Give the number of drivers bigger or equale to     '+str(min_Conducteur)+'    ')
    Conducteur=int(Conducteur)

6


In [ ]:
Slected_Terminal=np.array(Selected_Data['Terminal'])

Value_Terminal=[]
for i in range(len(Slected_Terminal)):
    if Slected_Terminal[i]=='T1':
        Value_Terminal.append(1)
    elif Slected_Terminal[i]=='T2':
        Value_Terminal.append(2)
    else:
        Value_Terminal.append(4)

print(Value_Terminal)
    

[2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 1, 4, 2, 2, 4, 2, 2, 2, 4, 2, 1, 4, 1, 2, 1, 2, 2, 4, 2, 2, 1, 2, 4, 2, 2, 4, 1, 4, 2, 1, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2]


In [50]:
# %%
# Import of the pyomo module
from pyomo.environ import *
from pyomo.opt import SolverFactory
import pyomo.environ

# Creation of a Concrete Model
model = ConcreteModel()

# %%
model.C = Set(initialize=range(Conducteur), doc='les Conducteur')
model.J = Set(initialize=range(len(Adj)), doc='les jobs')
model.A = Set(initialize=range(len(Ex[0])), doc='les arcs')
model.t = Set (initialize=[1,2,4], doc='Terminal')
# %%
model.n = Param(initialize=len(Adj), doc='le nombre de jobs')
model.c = Param(initialize=Conducteur, doc='le nombre de conducteur')
model.m = Param(initialize=len(Ex[1]), doc='les relations entre les arcs')
model.ex1 = Param(model.A,initialize=Ex[0], doc='extrémité 1')
model.ex2 = Param(model.A,initialize=Ex[1], doc='extrémité 2')
model.T = Param(model.J,initialize=Value_Terminal, doc='les Terminal Affecté')
# %%
model.x = Var(model.C, model.J,domain=Binary, doc='affectation conducteur')
model.alpha = Var(model.C, model.t,domain=Binary, doc='affectation conducteur au terminal')
model.v = Var(model.C,bounds=(0,None),domain=Integers, doc='les taches')
model.y = Var(model.t,bounds=(0,None),domain=Integers, doc='valeur de comparaison')

# %%
def Cotraint1(model,j):
  return sum(model.x[i,j] for i in model.C) == 1
model.C1 = Constraint(model.J, rule=Cotraint1, doc='verification daffectation')


def Contraint2(model,i,k):
  return ((model.x[i,model.ex1[k]]+model.x[i,model.ex2[k]])) <= 1  

model.C2 = Constraint (model.C,model.A, rule=Contraint2, doc='verification de non chevauchement ')

def Contraint3(model,i):
  return sum(model.x[i,j] for j in model.J)==model.v[i]

model.C3 = Constraint (model.C, rule=Contraint3, doc='une seul tache par conducteur')

def Contraint4(model,i,k):
  return (model.alpha[i,k]*model.v[i]<=model.y[k])

model.C4 = Constraint (model.C,model.t, rule=Contraint4, doc='maximiser')

def Contraint5(model,i):
  return sum(model.alpha[i,k] for k in model.t) == 1
model.C5 = Constraint(model.C, rule=Contraint5, doc='verification daffectation de terminal')

def Contraint6(model,i,j):
  return (model.alpha[i,model.T[j]] >= model.x[i,j] )
model.C6 = Constraint(model.C,model.J, rule=Contraint6, doc='verification daffectation au t')
# %%

# %%
def objective_rule(model):
  return sum(model.y[k] for k in model.t)
model.objective = Objective(rule=objective_rule, sense=minimize, doc='Define objective function')

# %%
def pyomo_postprocess(options=None, instance=None, results=None):
  model.x.display()
# %%


opt = SolverFactory("gurobi")
results = opt.solve(model,tee=True)
#sends results to stdout
results.write()
print("\nDisplaying Solution\n" + '-'*60)
pyomo_postprocess(None, model, results)
# %%




Set parameter Username
Academic license - for non-commercial use only - expires 2022-07-10
Read LP format model from file C:\Users\pc\AppData\Local\Temp\tmpl2wmibvx.pyomo.lp
Reading time = 0.03 seconds
x586: 916 rows, 586 columns, 2761 nonzeros
Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 916 rows, 586 columns and 2761 nonzeros
Model fingerprint: 0x35a48512
Model has 18 quadratic constraints
Variable types: 1 continuous, 585 integer (576 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 349 rows and 1 columns
Presolve time: 0.03s
Presolved: 603 rows, 603 columns, 2328 nonzeros
Variable types: 0 continuous, 603 integer (576 binary)
Found heuristic solution: objective 64.0000000



In [51]:
model.y.display()

y : valeur de comparaison
    Size=3, Index=t
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      1 :     0 :   7.0 :  None : False : False : Integers
      2 :     0 :  21.0 :  None : False : False : Integers
      4 :     0 :  12.0 :  None : False : False : Integers


In [52]:
model.v.display()
#verfy how much each driver is working per day

v : les taches
    Size=6, Index=C
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      0 :     0 :   7.0 :  None : False : False : Integers
      1 :     0 :  21.0 :  None : False : False : Integers
      2 :     0 :  12.0 :  None : False : False : Integers
      3 :     0 :  21.0 :  None : False : False : Integers
      4 :     0 :  21.0 :  None : False : False : Integers
      5 :     0 :  11.0 :  None : False : False : Integers


In [53]:
x=model.x
Group_co=[]
Conducteur_ID=[0]*len(Adj)
for i in model.C:
    Group_co.append([])
    for j in model.J:
        if x[i,j].value == 1:
            Group_co[i].append(j)
            Conducteur_ID[j]=i

print(Group_co)
print(Conducteur_ID)

[[36, 46, 48, 50, 56, 62, 65], [0, 3, 6, 10, 13, 16, 19, 23, 26, 28, 31, 41, 49, 51, 55, 57, 66, 71, 79, 83, 86], [20, 22, 24, 30, 33, 47, 53, 63, 73, 85, 87, 89], [1, 2, 8, 11, 15, 17, 32, 38, 39, 43, 45, 52, 59, 67, 69, 75, 77, 81, 82, 84, 91], [4, 5, 7, 12, 18, 21, 27, 34, 35, 42, 54, 60, 64, 68, 70, 72, 76, 78, 80, 90, 92], [9, 14, 25, 29, 37, 40, 44, 58, 61, 74, 88]]
[1, 3, 3, 1, 4, 4, 1, 4, 3, 5, 1, 3, 4, 1, 5, 3, 1, 3, 4, 1, 2, 4, 2, 1, 2, 5, 1, 4, 1, 5, 2, 1, 3, 2, 4, 4, 0, 5, 3, 3, 5, 1, 4, 3, 5, 3, 0, 2, 0, 1, 0, 1, 3, 2, 4, 1, 0, 1, 5, 3, 4, 5, 0, 2, 4, 0, 1, 3, 4, 3, 4, 1, 4, 2, 5, 3, 4, 3, 4, 1, 4, 3, 3, 1, 3, 2, 1, 2, 5, 2, 4, 3, 4]


In [54]:
Selected_Data['Conducteur_ID']=Conducteur_ID
Selected_Data.drop('DATETIME', inplace=True, axis=1)
Selected_Data.drop('Graph_intervale', inplace=True, axis=1)

Selected_Data.head

C:\Users\pc\AppData\Local\Temp/ipykernel_19668/1035486003.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Selected_Data['Conducteur_ID']=Conducteur_ID
c:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py:4901: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


<bound method NDFrame.head of           Date       HPA       HPD  Cie  Ligne Esc 1  Immat Type app   PKG  \
3   2022-04-09       NaN  08:00:00  DAH   6258   CZL  7TVUK    ATR72   PA1   
4   2022-04-09       NaN  08:00:00  DTH   2320   AZR  7TVCE     B738   PA1   
5   2022-04-09       NaN  08:15:00  DAH   6170   AAE  7TVUM    ATR72   PA1   
6   2022-04-09       NaN  08:45:00  DAH   6180   ORN  7TVUT    ATR72   PA1   
7   2022-04-09       NaN  08:45:00  DTH   1154   HME  7TVCD     B738  P10C   
..         ...       ...       ...  ...    ...   ...    ...      ...   ...   
91  2022-04-09  18:20:00       NaN  DAH   3017   IST  7TVKO     B738   P15   
92  2022-04-09       NaN  18:20:00  DAH   6026   CZL  7TVJU     B736  P11A   
93  2022-04-09       NaN  18:30:00  DAH   6106   ORN  7TVJS     B736    P9   
94  2022-04-09  18:40:00       NaN  DAH   6193   CZL  7TVKE     B738   P12   
95  2022-04-09       NaN  18:40:00  DAH   6006   AAE  7TVKL     B738  P10C   

         Remarque                

In [56]:

import xlwt
from tempfile import TemporaryFile

import xlwt
from xlwt.Workbook import *
from pandas import ExcelWriter
import xlsxwriter
book = pd.ExcelWriter('Conducteur'+str(Date)+'-'+str(Brigade)+'.xlsx', engine='xlsxwriter')
Selected_Data.to_excel(book, sheet_name='recaputulation ')

for i in model.C:
    DATA=Selected_Data.loc[Selected_Data['Conducteur_ID'] == i]
    DATA.drop('Conducteur_ID', inplace=True, axis=1)
    DATA.to_excel(book, sheet_name='Conducteur '+str(i+1))

book.save()


c:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py:4901: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [ ]:
# Slected_DATETIME= np.array(Selected_Data['DATETIME'])
# Slected_Terminal=np.array(Selected_Data['Terminal'])
# Slected_PKG=np.array(Selected_Data['PKG'])
# Slected_HPA=np.array(Selected_Data['HPA'])
# Slected_HPD=np.array(Selected_Data['HPD'])
# Slected_date=np.array(Selected_Data['Date'])
# Slected_Cie=np.array(Selected_Data['Cie'])
# Slected_Esc1=np.array(Selected_Data['Esc 1'])
# Slected_Ligne=np.array(Selected_Data['Ligne'])
# Slected_Immat=np.array(Selected_Data['Immat'])
# Slected_Immat=np.array(Selected_Data['Type app'])

# import xlwt
# from tempfile import TemporaryFile

# import xlwt
# from xlwt.Workbook import *
# from pandas import ExcelWriter
# import xlsxwriter
# book = pd.ExcelWriter('Conducteur'+str(Date)+'-'+str(Brigade)+'.xlsx', engine='xlsxwriter')
# for i in range(len(Group_co)):
#     data=None
#     Terminal=[]
#     PKG=[]
#     date=[]
#     HPA=[]
#     HPD=[]
#     for j in Group_co[i]:
#         date.append(Slected_date[j])
#         HPA.append(Slected_HPA[j])
#         HPD.append(Slected_HPD[j])
#         Terminal.append(Slected_Terminal[j])
#         PKG.append(Slected_PKG[j])
    
#     DATA=list(zip(date, HPA,HPD,Terminal,PKG))
#     data=pd.DataFrame(DATA,columns=['date','HPA','HPD','Terminal','PKG'])
#     data.to_excel(book, sheet_name='Conducteur '+str(i+1))

# book.save()


: 