In [194]:
from collections import deque
import numpy as np
import pandas as pd

import datetime as dt
from datetime import datetime, timedelta
import time
import math

Imprting Data from excel File using pandas lib

In [195]:
Data = pd.read_excel('Vol.xlsx', sheet_name='Vol')
Data.info

<bound method DataFrame.info of           Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
0   2022-04-09       NaN  07:15:00  DAH   4000    TUN  7TVKD     B738   P18   
1   2022-04-09       NaN  07:30:00  DTH   1400    RNS  7TVCL     DH8D   PA1   
2   2022-04-09       NaN  07:30:00  DTH   1408    RNS  7TVCR     DH8D   PA1   
3   2022-04-09       NaN  08:00:00  DAH   6258    CZL  7TVUK    ATR72   PA1   
4   2022-04-09       NaN  08:00:00  DTH   2320    AZR  7TVCE     B738   PA1   
..         ...       ...       ...  ...    ...    ...    ...      ...   ...   
189 2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   
190 2022-04-10  19:55:00       NaN  DAH   1041  7TVKK   B738      NCE   P19   
191 2022-04-10  20:30:00       NaN  DAH   4003  7TVKM   B738      TUN   P15   
192 2022-04-10       NaN  22:45:00  DAH   4062  7TVJA   A330      DXB   P21   
193 2022-04-10  22:50:00       NaN  AZA    802    NaN   A320      FCO   P16   

          Remarque 

In [196]:
Data.head

<bound method NDFrame.head of           Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
0   2022-04-09       NaN  07:15:00  DAH   4000    TUN  7TVKD     B738   P18   
1   2022-04-09       NaN  07:30:00  DTH   1400    RNS  7TVCL     DH8D   PA1   
2   2022-04-09       NaN  07:30:00  DTH   1408    RNS  7TVCR     DH8D   PA1   
3   2022-04-09       NaN  08:00:00  DAH   6258    CZL  7TVUK    ATR72   PA1   
4   2022-04-09       NaN  08:00:00  DTH   2320    AZR  7TVCE     B738   PA1   
..         ...       ...       ...  ...    ...    ...    ...      ...   ...   
189 2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   
190 2022-04-10  19:55:00       NaN  DAH   1041  7TVKK   B738      NCE   P19   
191 2022-04-10  20:30:00       NaN  DAH   4003  7TVKM   B738      TUN   P15   
192 2022-04-10       NaN  22:45:00  DAH   4062  7TVJA   A330      DXB   P21   
193 2022-04-10  22:50:00       NaN  AZA    802    NaN   A320      FCO   P16   

          Remarque   

In [197]:
Data.shape
Data= Data.astype({"Date": str}, errors='raise')

We needed to make the data col as string because pands automaticly detaxted dates , but it made it deficult for us to process 

In [198]:
Data.info()
print(Data['Date'])


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Date      194 non-null    object
 1   HPA       95 non-null     object
 2   HPD       99 non-null     object
 3   Cie       194 non-null    object
 4   Ligne     194 non-null    int64 
 5   Esc 1     172 non-null    object
 6   Immat     180 non-null    object
 7   Type app  194 non-null    object
 8   PKG       194 non-null    object
 9   Remarque  194 non-null    object
 10  Comment   170 non-null    object
 11  Terminal  194 non-null    object
dtypes: int64(1), object(11)
memory usage: 18.3+ KB
0      2022-04-09
1      2022-04-09
2      2022-04-09
3      2022-04-09
4      2022-04-09
          ...    
189    2022-04-10
190    2022-04-10
191    2022-04-10
192    2022-04-10
193    2022-04-10
Name: Date, Length: 194, dtype: object


In [199]:

Time=[]
for i in range (len(Data)):
    if pd.notna(Data['HPA'][i]) : #Convert heure prevu d'accostage and adding to her the exact date
        Time.append(str(Data["Date"][i])+" "+str(Data['HPA'][i]))
    elif pd.notna(Data['HPD'][i]) :#Convert heure prevu d'essacostage and adding to her the exact date
        Time.append(str(Data["Date"][i])+" "+str(Data['HPD'][i]))
    else:
        Time.append(float('nan'))

print(Time)
Data['DATETIME']=Time #creating a new col in the table with the datetime for the operation .
print(Data)

['2022-04-09 07:15:00', '2022-04-09 07:30:00', '2022-04-09 07:30:00', '2022-04-09 08:00:00', '2022-04-09 08:00:00', '2022-04-09 08:15:00', '2022-04-09 08:45:00', '2022-04-09 08:45:00', '2022-04-09 08:50:00', '2022-04-09 09:00:00', '2022-04-09 09:10:00', '2022-04-09 09:10:00', '2022-04-09 09:10:00', '2022-04-09 09:10:00', '2022-04-09 09:15:00', '2022-04-09 09:15:00', '2022-04-09 09:15:00', '2022-04-09 09:20:00', '2022-04-09 09:45:00', '2022-04-09 09:45:00', '2022-04-09 10:00:00', '2022-04-09 10:00:00', '2022-04-09 10:00:00', '2022-04-09 10:10:00', '2022-04-09 10:15:00', '2022-04-09 10:20:00', '2022-04-09 10:20:00', '2022-04-09 10:25:00', '2022-04-09 10:30:00', '2022-04-09 10:30:00', '2022-04-09 10:30:00', '2022-04-09 10:35:00', '2022-04-09 10:50:00', '2022-04-09 10:50:00', '2022-04-09 11:00:00', '2022-04-09 11:00:00', '2022-04-09 11:05:00', '2022-04-09 11:20:00', '2022-04-09 11:35:00', '2022-04-09 11:45:00', '2022-04-09 11:45:00', '2022-04-09 12:00:00', '2022-04-09 12:05:00', '2022-04-0

In [200]:

TimeGap=input('Give a Time GAP equal or bigger to 6  :') #input gap time based on the need and calculation 
TimeGap=int(TimeGap)
def Trans_to_min(x):
    D=x.day*24*60
    min = x.minute
    H = x.hour *60
    return int(D+min+H)
# this fenction transfer the date time into a number , we transfered the date into munites also , because in the night shift , the 00:00 comes after 23:00 , so we needed another variable to tell us that the day changed

Graph_intervale=[]

for i in range(len(Data)):
    try:
        Graph_intervale.append([])
        Time[i] = dt.datetime.strptime(str(Time[i]), '%Y-%d-%m %H:%M:%S')
        min= Time[i]- dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(min))
        max= Time[i]+ dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(max))
    except:
        Time[i] = dt.datetime.strptime(str(Time[i]), '%d-%m-%Y %H:%M:%S')
        min= Time[i]- dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(min))
        max= Time[i]+ dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(max)) 
print((Graph_intervale))
Data['Graph_intervale']=Graph_intervale


[[6190, 6200], [6205, 6215], [6205, 6215], [6235, 6245], [6235, 6245], [6250, 6260], [6280, 6290], [6280, 6290], [6285, 6295], [6295, 6305], [6305, 6315], [6305, 6315], [6305, 6315], [6305, 6315], [6310, 6320], [6310, 6320], [6310, 6320], [6315, 6325], [6340, 6350], [6340, 6350], [6355, 6365], [6355, 6365], [6355, 6365], [6365, 6375], [6370, 6380], [6375, 6385], [6375, 6385], [6380, 6390], [6385, 6395], [6385, 6395], [6385, 6395], [6390, 6400], [6405, 6415], [6405, 6415], [6415, 6425], [6415, 6425], [6420, 6430], [6435, 6445], [6450, 6460], [6460, 6470], [6460, 6470], [6475, 6485], [6480, 6490], [6500, 6510], [6505, 6515], [6505, 6515], [6535, 6545], [6540, 6550], [6545, 6555], [6550, 6560], [6555, 6565], [6555, 6565], [6560, 6570], [6570, 6580], [6615, 6625], [6625, 6635], [6625, 6635], [6625, 6635], [6625, 6635], [6630, 6640], [6655, 6665], [6665, 6675], [6670, 6680], [6670, 6680], [6675, 6685], [6675, 6685], [6680, 6690], [6690, 6700], [6705, 6715], [6715, 6725], [6715, 6725], [6715

we transftered into munites every variables for us to create an interval of time .

In [201]:
Brigade=[]
for i in range (len(Data)):
    if (Time[i].hour >=0 and Time[i].hour<=7) or (Time[i].hour >=19 and Time[i].hour<=23): 
        Brigade.append("Nuit")
    else:
        Brigade.append("Journee")
Data['Brigade']=Brigade
print(Data)

           Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
0    2022-04-09       NaN  07:15:00  DAH   4000    TUN  7TVKD     B738   P18   
1    2022-04-09       NaN  07:30:00  DTH   1400    RNS  7TVCL     DH8D   PA1   
2    2022-04-09       NaN  07:30:00  DTH   1408    RNS  7TVCR     DH8D   PA1   
3    2022-04-09       NaN  08:00:00  DAH   6258    CZL  7TVUK    ATR72   PA1   
4    2022-04-09       NaN  08:00:00  DTH   2320    AZR  7TVCE     B738   PA1   
..          ...       ...       ...  ...    ...    ...    ...      ...   ...   
189  2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   
190  2022-04-10  19:55:00       NaN  DAH   1041  7TVKK   B738      NCE   P19   
191  2022-04-10  20:30:00       NaN  DAH   4003  7TVKM   B738      TUN   P15   
192  2022-04-10       NaN  22:45:00  DAH   4062  7TVJA   A330      DXB   P21   
193  2022-04-10  22:50:00       NaN  AZA    802    NaN   A320      FCO   P16   

          Remarque                 Comm

In [202]:
#Select Brigate
Date=input('Input your the date you want')
Brigade=input('Input the brigade you want ')

In [203]:

if Brigade=='Journee':
    Selected_Data=Data.loc[(Data['Date'] == Date) & (Data['Brigade'] == Brigade) ]
if Brigade=='Nuit':
    Time01 = dt.datetime.strptime(str(Date)+" 19:00:00", '%Y-%m-%d %H:%M:%S')
    Time02 = dt.datetime.strptime(str(Date)+" 08:00:00", '%Y-%m-%d %H:%M:%S')

    Time01=Trans_to_min(Time01)
    Time02=Trans_to_min(Time02) + 24*60
    print(Time01)
    print(Time02)
    Selected=[]
    for i in range(len(Data)):
        Time = dt.datetime.strptime(Data['DATETIME'][i], '%Y-%m-%d %H:%M:%S')
        Time=Trans_to_min(Time)
        if Time >= Time01 and Time < Time02 :
            Selected.append(Data['DATETIME'][i])
    Selected_Data = Data.loc[Data['DATETIME'].isin(Selected)]

print(Selected_Data)


           Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
106  2022-04-10       NaN  08:00:00  DAH   6038  7TVUN  ATR72      BLJ   PA1   
107  2022-04-10       NaN  08:15:00  DAH   6170  7RVUK  ATR72      AAE   PA1   
108  2022-04-10       NaN  08:15:00  DAH   6216  7TVUO  ATR72      OGX   PA1   
109  2022-04-10  08:25:00       NaN  DTH   1903  7TVCD   B738      HME  P11A   
110  2022-04-10  08:30:00       NaN  VLG   7476    NaN   A321      BCN   P16   
..          ...       ...       ...  ...    ...    ...    ...      ...   ...   
185  2022-04-10       NaN  18:20:00  DAH   6106  7TVKP   B738      ORN    P9   
186  2022-04-10  18:30:00       NaN  DAH   6185  7TVKG   B738      ORN  P10C   
187  2022-04-10       NaN  18:30:00  DAH   6200  7TVUO  ATR72      GHA   PA1   
188  2022-04-10       NaN  18:30:00  DAH   6026  7TVKE   B738      CZL   P12   
189  2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   

          Remarque                 Comm

Slection of the brigade based on the need , the pd.loc will filter based on the condition ,but the indexes will stay the same.

In [204]:
Graph_intervale=Selected_Data["Graph_intervale"]
Graph_intervale=np.array(Graph_intervale) #doing array to remove the indexes from the selections before , also sice we require a type list for our code to work 
print(Graph_intervale)

Graph01=Selected_Data.loc[Selected_Data['Terminal'] == 'T1']
Graph01=np.array(Graph01["Graph_intervale"])
Graph02=Selected_Data.loc[Selected_Data['Terminal'] == 'T2']
Graph02=np.array(Graph02["Graph_intervale"])
Graph03=Selected_Data.loc[Selected_Data['Terminal'] == 'T4']
Graph03=np.array(Graph03["Graph_intervale"])

[list([6235, 6245]) list([6250, 6260]) list([6250, 6260])
 list([6260, 6270]) list([6265, 6275]) list([6275, 6285])
 list([6275, 6285]) list([6295, 6305]) list([6305, 6315])
 list([6310, 6320]) list([6325, 6335]) list([6330, 6340])
 list([6340, 6350]) list([6355, 6365]) list([6355, 6365])
 list([6360, 6370]) list([6365, 6375]) list([6370, 6380])
 list([6370, 6380]) list([6370, 6380]) list([6370, 6380])
 list([6375, 6385]) list([6375, 6385]) list([6380, 6390])
 list([6385, 6395]) list([6400, 6410]) list([6415, 6425])
 list([6435, 6445]) list([6435, 6445]) list([6440, 6450])
 list([6440, 6450]) list([6455, 6465]) list([6465, 6475])
 list([6470, 6480]) list([6475, 6485]) list([6485, 6495])
 list([6500, 6510]) list([6520, 6530]) list([6520, 6530])
 list([6525, 6535]) list([6530, 6540]) list([6550, 6560])
 list([6550, 6560]) list([6550, 6560]) list([6575, 6585])
 list([6595, 6605]) list([6595, 6605]) list([6600, 6610])
 list([6610, 6620]) list([6625, 6635]) list([6625, 6635])
 list([6645, 6

In [205]:
def Verify_in_interval(M1,M2):
    if M1[0]<=M2[0] and M1[1]>=M2[0]:
        return True
    elif M1[0]<=M2[1] and M1[1]>=M2[1]:
        return True
    else: 
        return False 
def   listAdj(M):
    listAdj=[]
    for i in range(len(M)):
        listAdj.append([])
        for j in [x for x in range(len(M)) if x != i]:
            if Verify_in_interval(M[i],M[j]) or Verify_in_interval(M[j],M[i]) :
                listAdj[i].append(j)
            else:
                pass
    return listAdj
            #print(listAdj[i])
    #print(listAdj[i])
# print(M)
Adj=listAdj(Graph_intervale)
print(Adj)

Adj01=listAdj(Graph01)
Adj02=listAdj(Graph02)
Adj03=listAdj(Graph03)

[[], [2, 3], [1, 3], [1, 2, 4], [3, 5, 6], [4, 6], [4, 5], [8], [7, 9], [8], [11], [10, 12], [11], [14, 15, 16], [13, 15, 16], [13, 14, 16, 17, 18, 19, 20], [13, 14, 15, 17, 18, 19, 20, 21, 22], [15, 16, 18, 19, 20, 21, 22, 23], [15, 16, 17, 19, 20, 21, 22, 23], [15, 16, 17, 18, 20, 21, 22, 23], [15, 16, 17, 18, 19, 21, 22, 23], [16, 17, 18, 19, 20, 22, 23, 24], [16, 17, 18, 19, 20, 21, 23, 24], [17, 18, 19, 20, 21, 22, 24], [21, 22, 23], [], [], [28, 29, 30], [27, 29, 30], [27, 28, 30], [27, 28, 29], [32], [31, 33, 34], [32, 34], [32, 33, 35], [34], [], [38, 39, 40], [37, 39, 40], [37, 38, 40], [37, 38, 39], [42, 43], [41, 43], [41, 42], [], [46, 47], [45, 47], [45, 46, 48], [47], [50], [49], [52, 53, 54], [51, 53, 54], [51, 52, 54, 55], [51, 52, 53, 55, 56, 57], [53, 54, 56, 57, 58], [54, 55, 57, 58, 59], [54, 55, 56, 58, 59], [55, 56, 57, 59], [56, 57, 58, 60, 61], [59, 61], [59, 60], [], [], [65, 66], [64, 66], [64, 65], [68], [67], [70, 71, 72, 73], [69, 71, 72, 73], [69, 70, 72, 

In [206]:
def matriceAdj(Adj):
    Mat=[]
    for i in range( len(Adj)):
        Mat.append([])
        for j in range( len(Adj)):
            Mat[i].append(0)
            for k in range(len(Adj[i])):
                if j==Adj[i][k]:
                    Mat[i][j]=1
    return Mat

In [207]:
def arret(M):
    ex=[[],[]]
    for i in range (len(M)-1):
        for j in range(i+1,len(M)):
            if M[i][j]==1:
                ex[0].append(i)
                ex[1].append(j)
    return ex
#Create a list of start and end of each arret in our graph

In [208]:
Mat=matriceAdj(Adj)
Mat= np.array(Mat)
print (Mat)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 1 1 0]]


In [209]:
Ex=arret(Mat)
print("ex1= ",Ex[0])
print("ex2= ",Ex[1])


print(len(Ex[0]))

ex1=  [1, 1, 2, 3, 4, 4, 5, 7, 8, 10, 11, 13, 13, 13, 14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 23, 27, 27, 27, 28, 28, 29, 31, 32, 32, 33, 34, 37, 37, 37, 38, 38, 39, 41, 41, 42, 45, 45, 46, 47, 49, 51, 51, 51, 52, 52, 53, 53, 54, 54, 54, 55, 55, 55, 56, 56, 56, 57, 57, 58, 59, 59, 60, 64, 64, 65, 67, 69, 69, 69, 69, 70, 70, 70, 71, 71, 72, 76, 76, 76, 77, 77, 78, 78, 78, 78, 79, 79, 79, 80, 80, 80, 81, 81, 82]
ex2=  [2, 3, 3, 4, 5, 6, 6, 8, 9, 11, 12, 14, 15, 16, 15, 16, 16, 17, 18, 19, 20, 17, 18, 19, 20, 21, 22, 18, 19, 20, 21, 22, 23, 19, 20, 21, 22, 23, 20, 21, 22, 23, 21, 22, 23, 22, 23, 24, 23, 24, 24, 28, 29, 30, 29, 30, 30, 32, 33, 34, 34, 35, 38, 39, 40, 39, 40, 40, 42, 43, 43, 46, 47, 47, 48, 50, 52, 53, 54, 53, 54, 54, 55, 55, 56, 57, 56, 57, 58, 57, 58, 59, 58, 59, 59, 60, 61, 61, 65, 66, 66, 68, 70, 71, 72, 73, 71, 72, 73, 72, 73, 73, 77, 78, 79, 78, 79, 79, 80, 81, 82, 

In [210]:
def Gloton(Adj):
    n=len(Adj)
    NC=dict()
    C=[0 for k in range(n)]
    for i in range(n):
        NC[i]=[]
    def  rajouter(k,NC):
        if ((k in NC)==True):
            return NC
        else:
            NC.append(k)
            return NC
    i=0
    while i<=n-1:
        exist=True
        k=0
        while (exist==True):
            exist=k in NC[i]
            if (exist==True):
                k+=1
        C[i]=k    
        for j in range(len(Adj[i])):
            voisin=Adj[i][j]
            NC[voisin]=rajouter(k,NC[voisin])
        i+=1
    return C
# C=Gloton(Adj)
C1=Gloton(Adj01)
C2=Gloton(Adj02)
C3=Gloton(Adj03)
def Minimum(C):
    min_Conducteur=0
    for i in C:
        if min_Conducteur<=i:
            min_Conducteur=i
    min_Conducteur+=1
    return min_Conducteur

min_Conducteur=(Minimum(C1)+Minimum(C2)+Minimum(C3))

print(min_Conducteur)
Conducteur=0
while (Conducteur<min_Conducteur):
    Conducteur=input('Give the number of drivers bigger or equale to     '+str(min_Conducteur)+'    ')
    Conducteur=int(Conducteur)

10


In [211]:
Slected_Terminal=np.array(Selected_Data['Terminal'])

Value_Terminal=[]
for i in range(len(Slected_Terminal)):
    if Slected_Terminal[i]=='T1':
        Value_Terminal.append(1)
    elif Slected_Terminal[i]=='T2':
        Value_Terminal.append(2)
    else:
        Value_Terminal.append(4)

print(Value_Terminal)
    

[2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 4, 4, 1, 4, 2, 2, 2, 4, 4, 1, 2, 1, 1, 2, 2, 2, 4, 4, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 4, 1, 2, 4, 2, 2, 1, 2, 2, 4, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2]


In [212]:
# %%
# Import of the pyomo module
from pyomo.environ import *
from pyomo.opt import SolverFactory
import pyomo.environ

# Creation of a Concrete Model
model = ConcreteModel()

# %%
model.C = Set(initialize=range(Conducteur), doc='les Conducteur')
model.J = Set(initialize=range(len(Adj)), doc='les jobs')
model.A = Set(initialize=range(len(Ex[0])), doc='les arcs')
model.t = Set (initialize=[1,2,4], doc='Terminal')
# %%
model.n = Param(initialize=len(Adj), doc='le nombre de jobs')
model.c = Param(initialize=Conducteur, doc='le nombre de conducteur')
model.m = Param(initialize=len(Ex[1]), doc='les relations entre les arcs')
model.ex1 = Param(model.A,initialize=Ex[0], doc='extrémité 1')
model.ex2 = Param(model.A,initialize=Ex[1], doc='extrémité 2')
model.T = Param(model.J,initialize=Value_Terminal, doc='les Terminal Affecté')
# %%
model.x = Var(model.C, model.J,domain=Binary, doc='affectation conducteur')
model.alpha = Var(model.C, model.t,domain=Binary, doc='affectation conducteur au terminal')
model.v = Var(model.C,bounds=(0,None),domain=Integers, doc='les taches')
model.y = Var(bounds=(0,None),domain=Integers, doc='valeur de comparaison')

# %%
def Cotraint1(model,j):
  return sum(model.x[i,j] for i in model.C) == 1
model.C1 = Constraint(model.J, rule=Cotraint1, doc='verification daffectation')


def Contraint2(model,i,k):
  return ((model.x[i,model.ex1[k]]+model.x[i,model.ex2[k]])) <= 1  

model.C2 = Constraint (model.C,model.J, rule=Contraint2, doc='verification de non chevauchement ')

def Contraint3(model,i):
  return sum(model.x[i,j] for j in model.J)==model.v[i]

model.C3 = Constraint (model.C, rule=Contraint3, doc='une seul tache par conducteur')

def Contraint4(model,i):
  return (model.v[i]<=model.y)

model.C4 = Constraint (model.C, rule=Contraint4, doc='maximiser')

def Contraint5(model,i):
  return sum(model.alpha[i,k] for k in model.t) == 1
model.C5 = Constraint(model.C, rule=Contraint5, doc='verification daffectation de terminal')

def Contraint6(model,i,j):
  return (model.alpha[i,model.T[j]] >= model.x[i,j] )
model.C6 = Constraint(model.C,model.J, rule=Contraint6, doc='verification daffectation au t')
# %%

# %%
def objective_rule(model):
  return model.y
model.objective = Objective(rule=objective_rule, sense=minimize, doc='Define objective function')

# %%
def pyomo_postprocess(options=None, instance=None, results=None):
  model.x.display()
# %%


opt = SolverFactory("gurobi")
results = opt.solve(model,tee=True)
#sends results to stdout
results.write()
print("\nDisplaying Solution\n" + '-'*60)
pyomo_postprocess(None, model, results)
# %%




Set parameter Username
Academic license - for non-commercial use only - expires 2022-07-10
Read LP format model from file C:\Users\pc\AppData\Local\Temp\tmphj4byei6.pyomo.lp
Reading time = 0.01 seconds
x882: 1795 rows, 882 columns, 5101 nonzeros
Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 1795 rows, 882 columns and 5101 nonzeros
Model fingerprint: 0x4a90b45b
Variable types: 1 continuous, 881 integer (870 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 871 rows and 11 columns
Presolve time: 0.01s
Presolved: 924 rows, 871 columns, 3870 nonzeros
Variable types: 0 continuous, 871 integer (870 binary)

Root relaxation: objective 8.400000e+00, 788 iterations, 0.03 seconds (0.03 work units)

    Nodes    |    Current Node    |     Objective Bounds  

In [213]:
model.v.display()
#verfy how much each driver is working per day

v : les taches
    Size=10, Index=C
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      0 :     0 :   4.0 :  None : False : False : Integers
      1 :     0 :   7.0 :  None : False : False : Integers
      2 :     0 :   8.0 :  None : False : False : Integers
      3 :     0 :  13.0 :  None : False : False : Integers
      4 :     0 :  13.0 :  None : False : False : Integers
      5 :     0 :  13.0 :  None : False : False : Integers
      6 :     0 :   7.0 :  None : False : False : Integers
      7 :     0 :   2.0 :  None : False : False : Integers
      8 :     0 :   5.0 :  None : False : False : Integers
      9 :     0 :  12.0 :  None : False : False : Integers


In [214]:
x=model.x
Group_co=[]
Conducteur_ID=[0]*len(Adj)
for i in model.C:
    Group_co.append([])
    for j in model.J:
        if x[i,j].value == 1:
            Group_co[i].append(j)
            Conducteur_ID[j]=i

print(Group_co)
print(Conducteur_ID)

[[10, 13, 22, 37], [23, 30, 33, 41, 47, 59, 64], [4, 8, 21, 29, 56, 67, 71, 76], [2, 6, 14, 18, 25, 26, 27, 31, 39, 48, 50, 51, 66], [16, 35, 49, 53, 62, 65, 68, 69, 73, 77, 80, 81, 83], [0, 3, 5, 7, 9, 11, 15, 36, 42, 46, 52, 74, 79], [20, 38, 55, 61, 70, 72, 78], [32, 40], [17, 24, 28, 58, 75], [1, 12, 19, 34, 43, 44, 45, 54, 57, 60, 63, 82]]
[5, 9, 3, 5, 2, 5, 3, 5, 2, 5, 0, 5, 9, 0, 3, 5, 4, 8, 3, 9, 6, 2, 0, 1, 8, 3, 3, 3, 8, 2, 1, 3, 7, 1, 9, 4, 5, 0, 6, 3, 7, 1, 5, 9, 9, 9, 5, 1, 3, 4, 3, 3, 5, 4, 9, 6, 2, 9, 8, 1, 9, 6, 4, 9, 1, 4, 3, 2, 4, 4, 6, 2, 6, 4, 5, 8, 2, 4, 6, 5, 4, 4, 9, 4]


In [215]:
Selected_Data['Conducteur_ID']=Conducteur_ID
Selected_Data.drop('DATETIME', inplace=True, axis=1)
Selected_Data.drop('Graph_intervale', inplace=True, axis=1)

Selected_Data.head

C:\Users\pc\AppData\Local\Temp/ipykernel_1552/1035486003.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Selected_Data['Conducteur_ID']=Conducteur_ID
c:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py:4901: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


<bound method NDFrame.head of            Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
106  2022-04-10       NaN  08:00:00  DAH   6038  7TVUN  ATR72      BLJ   PA1   
107  2022-04-10       NaN  08:15:00  DAH   6170  7RVUK  ATR72      AAE   PA1   
108  2022-04-10       NaN  08:15:00  DAH   6216  7TVUO  ATR72      OGX   PA1   
109  2022-04-10  08:25:00       NaN  DTH   1903  7TVCD   B738      HME  P11A   
110  2022-04-10  08:30:00       NaN  VLG   7476    NaN   A321      BCN   P16   
..          ...       ...       ...  ...    ...    ...    ...      ...   ...   
185  2022-04-10       NaN  18:20:00  DAH   6106  7TVKP   B738      ORN    P9   
186  2022-04-10  18:30:00       NaN  DAH   6185  7TVKG   B738      ORN  P10C   
187  2022-04-10       NaN  18:30:00  DAH   6200  7TVUO  ATR72      GHA   PA1   
188  2022-04-10       NaN  18:30:00  DAH   6026  7TVKE   B738      CZL   P12   
189  2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   

         

In [216]:

import xlwt
from tempfile import TemporaryFile

import xlwt
from xlwt.Workbook import *
from pandas import ExcelWriter
import xlsxwriter
book = pd.ExcelWriter('Conducteur'+str(Date)+'-'+str(Brigade)+'.xlsx', engine='xlsxwriter')
for i in model.C:
    DATA=Selected_Data.loc[Selected_Data['Conducteur_ID'] == i]
    DATA.drop('Conducteur_ID', inplace=True, axis=1)
    DATA.to_excel(book, sheet_name='Conducteur '+str(i+1))

book.save()


c:\Users\pc\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py:4901: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [217]:
# Slected_DATETIME= np.array(Selected_Data['DATETIME'])
# Slected_Terminal=np.array(Selected_Data['Terminal'])
# Slected_PKG=np.array(Selected_Data['PKG'])
# Slected_HPA=np.array(Selected_Data['HPA'])
# Slected_HPD=np.array(Selected_Data['HPD'])
# Slected_date=np.array(Selected_Data['Date'])
# Slected_Cie=np.array(Selected_Data['Cie'])
# Slected_Esc1=np.array(Selected_Data['Esc 1'])
# Slected_Ligne=np.array(Selected_Data['Ligne'])
# Slected_Immat=np.array(Selected_Data['Immat'])
# Slected_Immat=np.array(Selected_Data['Type app'])

# import xlwt
# from tempfile import TemporaryFile

# import xlwt
# from xlwt.Workbook import *
# from pandas import ExcelWriter
# import xlsxwriter
# book = pd.ExcelWriter('Conducteur'+str(Date)+'-'+str(Brigade)+'.xlsx', engine='xlsxwriter')
# for i in range(len(Group_co)):
#     data=None
#     Terminal=[]
#     PKG=[]
#     date=[]
#     HPA=[]
#     HPD=[]
#     for j in Group_co[i]:
#         date.append(Slected_date[j])
#         HPA.append(Slected_HPA[j])
#         HPD.append(Slected_HPD[j])
#         Terminal.append(Slected_Terminal[j])
#         PKG.append(Slected_PKG[j])
    
#     DATA=list(zip(date, HPA,HPD,Terminal,PKG))
#     data=pd.DataFrame(DATA,columns=['date','HPA','HPD','Terminal','PKG'])
#     data.to_excel(book, sheet_name='Conducteur '+str(i+1))

# book.save()
