In [52]:
from collections import deque
import numpy as np
import pandas as pd

import datetime as dt
from datetime import *

Imprting Data from excel File using pandas lib

In [53]:
Data = pd.read_excel('Vol.xlsx', sheet_name='Vol')
Data.info

<bound method DataFrame.info of           Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
0   2022-04-09       NaN  07:15:00  DAH   4000    TUN  7TVKD     B738   P18   
1   2022-04-09       NaN  07:30:00  DTH   1400    RNS  7TVCL     DH8D   PA1   
2   2022-04-09       NaN  07:30:00  DTH   1408    RNS  7TVCR     DH8D   PA1   
3   2022-04-09       NaN  08:00:00  DAH   6258    CZL  7TVUK    ATR72   PA1   
4   2022-04-09       NaN  08:00:00  DTH   2320    AZR  7TVCE     B738   PA1   
..         ...       ...       ...  ...    ...    ...    ...      ...   ...   
189 2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   
190 2022-04-10  19:55:00       NaN  DAH   1041  7TVKK   B738      NCE   P19   
191 2022-04-10  20:30:00       NaN  DAH   4003  7TVKM   B738      TUN   P15   
192 2022-04-10       NaN  22:45:00  DAH   4062  7TVJA   A330      DXB   P21   
193 2022-04-10  22:50:00       NaN  AZA    802    NaN   A320      FCO   P16   

          Remarque 

In [54]:
Data.head

<bound method NDFrame.head of           Date       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
0   2022-04-09       NaN  07:15:00  DAH   4000    TUN  7TVKD     B738   P18   
1   2022-04-09       NaN  07:30:00  DTH   1400    RNS  7TVCL     DH8D   PA1   
2   2022-04-09       NaN  07:30:00  DTH   1408    RNS  7TVCR     DH8D   PA1   
3   2022-04-09       NaN  08:00:00  DAH   6258    CZL  7TVUK    ATR72   PA1   
4   2022-04-09       NaN  08:00:00  DTH   2320    AZR  7TVCE     B738   PA1   
..         ...       ...       ...  ...    ...    ...    ...      ...   ...   
189 2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   
190 2022-04-10  19:55:00       NaN  DAH   1041  7TVKK   B738      NCE   P19   
191 2022-04-10  20:30:00       NaN  DAH   4003  7TVKM   B738      TUN   P15   
192 2022-04-10       NaN  22:45:00  DAH   4062  7TVJA   A330      DXB   P21   
193 2022-04-10  22:50:00       NaN  AZA    802    NaN   A320      FCO   P16   

          Remarque   

In [55]:
Data.shape
Data= Data.astype({"Date": str}, errors='raise')

KeyError: 'Only a column name can be used for the key in a dtype mappings argument.'

We needed to make the data col as string because pands automaticly detaxted dates , but it made it deficult for us to process 

In [ ]:
Data.info()
print(Data['Date'])


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      194 non-null    datetime64[ns]
 1   HPA       95 non-null     object        
 2   HPD       99 non-null     object        
 3   Cie       194 non-null    object        
 4   Ligne     194 non-null    int64         
 5   Esc 1     172 non-null    object        
 6   Immat     180 non-null    object        
 7   Type app  194 non-null    object        
 8   PKG       194 non-null    object        
 9   Remarque  194 non-null    object        
 10  Comment   170 non-null    object        
 11  Terminal  194 non-null    object        
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 18.3+ KB


KeyError: 'DATE'

In [ ]:

Time=[]
for i in range (len(Data)):
    if pd.notna(Data['HPA'][i]) : #Convert heure prevu d'accostage and adding to her the exact date
        Time.append(str(Data["Date"][i])+" "+str(Data['HPA'][i]))
    elif pd.notna(Data['HPD'][i]) :#Convert heure prevu d'essacostage and adding to her the exact date
        Time.append(str(Data["Date"][i])+" "+str(Data['HPD'][i]))
    else:
        Time.append(float('nan'))

print(Time)
Data['DATETIME']=Time #creating a new col in the table with the datetime for the operation .
print(Data)

['2022-04-09 07:15:00', '2022-04-09 07:30:00', '2022-04-09 07:30:00', '2022-04-09 08:00:00', '2022-04-09 08:00:00', '2022-04-09 08:15:00', '2022-04-09 08:45:00', '2022-04-09 08:45:00', '2022-04-09 08:50:00', '2022-04-09 09:00:00', '2022-04-09 09:10:00', '2022-04-09 09:10:00', '2022-04-09 09:10:00', '2022-04-09 09:10:00', '2022-04-09 09:15:00', '2022-04-09 09:15:00', '2022-04-09 09:15:00', '2022-04-09 09:20:00', '2022-04-09 09:45:00', '2022-04-09 09:45:00', '2022-04-09 10:00:00', '2022-04-09 10:00:00', '2022-04-09 10:00:00', '2022-04-09 10:10:00', '2022-04-09 10:15:00', '2022-04-09 10:20:00', '2022-04-09 10:20:00', '2022-04-09 10:25:00', '2022-04-09 10:30:00', '2022-04-09 10:30:00', '2022-04-09 10:30:00', '2022-04-09 10:35:00', '2022-04-09 10:50:00', '2022-04-09 10:50:00', '2022-04-09 11:00:00', '2022-04-09 11:00:00', '2022-04-09 11:05:00', '2022-04-09 11:20:00', '2022-04-09 11:35:00', '2022-04-09 11:45:00', '2022-04-09 11:45:00', '2022-04-09 12:00:00', '2022-04-09 12:05:00', '2022-04-0

In [ ]:

TimeGap=input('Give a Time GAP') #input gap time based on the need and calculation 
TimeGap=int(TimeGap)
def Trans_to_min(x):
    D=x.day*24*60
    min = x.minute
    H = x.hour *60
    return int(D+min+H)
# this fenction transfer the date time into a number , we transfered the date into munites also , because in the night shift , the 00:00 comes after 23:00 , so we needed another variable to tell us that the day changed

Graph_intervale=[]

for i in range(len(Data)):
    try:
        Graph_intervale.append([])
        Time[i] = dt.datetime.strptime(str(Time[i]), '%Y-%d-%m %H:%M:%S')
        min= Time[i]- dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(min))
        max= Time[i]+ dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(max))
    except:
        Time[i] = dt.datetime.strptime(str(Time[i]), '%d-%m-%Y %H:%M:%S')
        min= Time[i]- dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(min))
        max= Time[i]+ dt.timedelta(minutes=TimeGap//2)
        Graph_intervale[i].append(Trans_to_min(max)) 
print((Graph_intervale))
Data['Graph_intervale']=Graph_intervale


[[6193, 6197], [6208, 6212], [6208, 6212], [6238, 6242], [6238, 6242], [6253, 6257], [6283, 6287], [6283, 6287], [6288, 6292], [6298, 6302], [6308, 6312], [6308, 6312], [6308, 6312], [6308, 6312], [6313, 6317], [6313, 6317], [6313, 6317], [6318, 6322], [6343, 6347], [6343, 6347], [6358, 6362], [6358, 6362], [6358, 6362], [6368, 6372], [6373, 6377], [6378, 6382], [6378, 6382], [6383, 6387], [6388, 6392], [6388, 6392], [6388, 6392], [6393, 6397], [6408, 6412], [6408, 6412], [6418, 6422], [6418, 6422], [6423, 6427], [6438, 6442], [6453, 6457], [6463, 6467], [6463, 6467], [6478, 6482], [6483, 6487], [6503, 6507], [6508, 6512], [6508, 6512], [6538, 6542], [6543, 6547], [6548, 6552], [6553, 6557], [6558, 6562], [6558, 6562], [6563, 6567], [6573, 6577], [6618, 6622], [6628, 6632], [6628, 6632], [6628, 6632], [6628, 6632], [6633, 6637], [6658, 6662], [6668, 6672], [6673, 6677], [6673, 6677], [6678, 6682], [6678, 6682], [6683, 6687], [6693, 6697], [6708, 6712], [6718, 6722], [6718, 6722], [6718

we transftered into munites every variables for us to create an interval of time .

In [ ]:
Brigade=[]
for i in range (len(Data)):
    if (Time[i].hour >=0 and Time[i].hour<=7) or (Time[i].hour >=19 and Time[i].hour<=23): 
        Brigade.append("Nuit")
    else:
        Brigade.append("Journee")
Data['Brigade']=Brigade
print(Data)

           DATE       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
0    2022-04-09       NaN  07:15:00  DAH   4000    TUN  7TVKD     B738   P18   
1    2022-04-09       NaN  07:30:00  DTH   1400    RNS  7TVCL     DH8D   PA1   
2    2022-04-09       NaN  07:30:00  DTH   1408    RNS  7TVCR     DH8D   PA1   
3    2022-04-09       NaN  08:00:00  DAH   6258    CZL  7TVUK    ATR72   PA1   
4    2022-04-09       NaN  08:00:00  DTH   2320    AZR  7TVCE     B738   PA1   
..          ...       ...       ...  ...    ...    ...    ...      ...   ...   
189  2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   
190  2022-04-10  19:55:00       NaN  DAH   1041  7TVKK   B738      NCE   P19   
191  2022-04-10  20:30:00       NaN  DAH   4003  7TVKM   B738      TUN   P15   
192  2022-04-10       NaN  22:45:00  DAH   4062  7TVJA   A330      DXB   P21   
193  2022-04-10  22:50:00       NaN  AZA    802    NaN   A320      FCO   P16   

          Remarque                 Comm

In [ ]:
#Select Brigate
Date=input('Input your the date you want')
Brigade=input('Input the brigade you want ')

In [ ]:

if Brigade=='Journee':
    Selected_Data=Data.loc[(Data['DATE'] == Date) & (Data['Brigade'] == Brigade) ]
if Brigade=='Nuit':
    Time01 = dt.datetime.strptime(str(Date)+" 19:00:00", '%Y-%m-%d %H:%M:%S')
    Time02 = dt.datetime.strptime(str(Date)+" 08:00:00", '%Y-%m-%d %H:%M:%S')

    Time01=Trans_to_min(Time01)
    Time02=Trans_to_min(Time02) + 24*60
    print(Time01)
    print(Time02)
    Selected=[]
    for i in range(len(Data)):
        Time = dt.datetime.strptime(Data['DATETIME'][i], '%Y-%m-%d %H:%M:%S')
        Time=Trans_to_min(Time)
        if Time >= Time01 and Time < Time02 :
            Selected.append(Data['DATETIME'][i])
    Selected_Data = Data.loc[Data['DATETIME'].isin(Selected)]

print(Selected_Data)


           DATE       HPA       HPD  Cie  Ligne  Esc 1  Immat Type app   PKG  \
106  2022-04-10       NaN  08:00:00  DAH   6038  7TVUN  ATR72      BLJ   PA1   
107  2022-04-10       NaN  08:15:00  DAH   6170  7RVUK  ATR72      AAE   PA1   
108  2022-04-10       NaN  08:15:00  DAH   6216  7TVUO  ATR72      OGX   PA1   
109  2022-04-10  08:25:00       NaN  DTH   1903  7TVCD   B738      HME  P11A   
110  2022-04-10  08:30:00       NaN  VLG   7476    NaN   A321      BCN   P16   
..          ...       ...       ...  ...    ...    ...    ...      ...   ...   
185  2022-04-10       NaN  18:20:00  DAH   6106  7TVKP   B738      ORN    P9   
186  2022-04-10  18:30:00       NaN  DAH   6185  7TVKG   B738      ORN  P10C   
187  2022-04-10       NaN  18:30:00  DAH   6200  7TVUO  ATR72      GHA   PA1   
188  2022-04-10       NaN  18:30:00  DAH   6026  7TVKE   B738      CZL   P12   
189  2022-04-10       NaN  18:40:00  DAH   6006  7TVKD   B738      AAE  P11A   

          Remarque                 Comm

Slection of the brigade based on the need , the pd.loc will filter based on the condition ,but the indexes will stay the same.

In [ ]:
Graph_intervale=Selected_Data["Graph_intervale"]
Graph_intervale=np.array(Graph_intervale) #doing array to remove the indexes from the selections before , also sice we require a type list for our code to work 
print(Graph_intervale)

[list([6238, 6242]) list([6253, 6257]) list([6253, 6257])
 list([6263, 6267]) list([6268, 6272]) list([6278, 6282])
 list([6278, 6282]) list([6298, 6302]) list([6308, 6312])
 list([6313, 6317]) list([6328, 6332]) list([6333, 6337])
 list([6343, 6347]) list([6358, 6362]) list([6358, 6362])
 list([6363, 6367]) list([6368, 6372]) list([6373, 6377])
 list([6373, 6377]) list([6373, 6377]) list([6373, 6377])
 list([6378, 6382]) list([6378, 6382]) list([6383, 6387])
 list([6388, 6392]) list([6403, 6407]) list([6418, 6422])
 list([6438, 6442]) list([6438, 6442]) list([6443, 6447])
 list([6443, 6447]) list([6458, 6462]) list([6468, 6472])
 list([6473, 6477]) list([6478, 6482]) list([6488, 6492])
 list([6503, 6507]) list([6523, 6527]) list([6523, 6527])
 list([6528, 6532]) list([6533, 6537]) list([6553, 6557])
 list([6553, 6557]) list([6553, 6557]) list([6578, 6582])
 list([6598, 6602]) list([6598, 6602]) list([6603, 6607])
 list([6613, 6617]) list([6628, 6632]) list([6628, 6632])
 list([6648, 6

In [ ]:
def Verify_in_interval(M1,M2):
    if M1[0]<=M2[0] and M1[1]>=M2[0]:
        return True
    elif M1[0]<=M2[1] and M1[1]>=M2[1]:
        return True
    else: 
        return False 
def   listAdj(M):
    listAdj=[]
    for i in range(len(M)):
        listAdj.append([])
        for j in [x for x in range(len(M)) if x != i]:
            if Verify_in_interval(M[i],M[j]) or Verify_in_interval(M[j],M[i]) :
                listAdj[i].append(j)
            else:
                pass
    return listAdj
            #print(listAdj[i])
    #print(listAdj[i])
# print(M)
Adj=listAdj(Graph_intervale)
print(Adj)

[[], [2], [1], [], [], [6], [5], [], [], [], [], [], [], [14], [13], [], [], [18, 19, 20], [17, 19, 20], [17, 18, 20], [17, 18, 19], [22], [21], [], [], [], [], [28], [27], [30], [29], [], [], [], [], [], [], [38], [37], [], [], [42, 43], [41, 43], [41, 42], [], [46], [45], [], [], [50], [49], [52], [51], [], [], [], [57], [56], [], [], [61], [60], [], [], [], [], [], [], [], [], [], [72, 73], [71, 73], [71, 72], [], [], [77], [76], [79], [78], [81, 82], [80, 82], [80, 81], []]


In [ ]:
def matriceAdj(Adj):
    Mat=[]
    for i in range( len(Adj)):
        Mat.append([])
        for j in range( len(Adj)):
            Mat[i].append(0)
            for k in range(len(Adj[i])):
                if j==Adj[i][k]:
                    Mat[i][j]=1
    return Mat

In [ ]:
def arret(M):
    ex=[[],[]]
    for i in range (len(M)-1):
        for j in range(i+1,len(M)):
            if M[i][j]==1:
                ex[0].append(i)
                ex[1].append(j)
    return ex
#Create a list of start and end of each arret in our graph

In [ ]:
Mat=matriceAdj(Adj)
Mat= np.array(Mat)
print (Mat)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
Ex=arret(Mat)
print("ex1= ",Ex[0])
print("ex2= ",Ex[1])


print(len(Ex[0]))

ex1=  [1, 5, 13, 17, 17, 17, 18, 18, 19, 21, 27, 29, 37, 41, 41, 42, 45, 49, 51, 56, 60, 71, 71, 72, 76, 78, 80, 80, 81]
ex2=  [2, 6, 14, 18, 19, 20, 19, 20, 20, 22, 28, 30, 38, 42, 43, 43, 46, 50, 52, 57, 61, 72, 73, 73, 77, 79, 81, 82, 82]
29


In [ ]:
def Gloton(Adj):
    n=len(Adj)
    NC=dict()
    C=[0 for k in range(n)]
    for i in range(n):
        NC[i]=[]
    def  rajouter(k,NC):
        if ((k in NC)==True):
            return NC
        else:
            NC.append(k)
            return NC
    i=0
    while i<=n-1:
        exist=True
        k=0
        while (exist==True):
            exist=k in NC[i]
            if (exist==True):
                k+=1
        C[i]=k    
        for j in range(len(Adj[i])):
            voisin=Adj[i][j]
            NC[voisin]=rajouter(k,NC[voisin])
        i+=1
    return C
C=Gloton(Adj)
print(C)
min_Conducteur=0
for i in C:
    if min_Conducteur<=i:
        min_Conducteur=i
min_Conducteur+=1
print(min_Conducteur)
Conducteur=0
while (Conducteur<min_Conducteur):
    Conducteur=input('Give the number of drivers bigger or equale to     '+str(min_Conducteur))
    Conducteur=int(Conducteur)

[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 3, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 0, 1, 2, 0]
4


In [ ]:
Slected_Terminal=np.array(Selected_Data['Terminal'])

Value_Terminal=[]
for i in range(len(Slected_Terminal)):
    if Slected_Terminal[i]=='T1':
        Value_Terminal.append(1)
    elif Slected_Terminal[i]=='T2':
        Value_Terminal.append(2)
    else:
        Value_Terminal.append(4)

print(Value_Terminal[83])
    

2


In [ ]:
Conducteur=20
print(range(len(Slected_Terminal)))

range(0, 84)


In [ ]:
# %%
# Import of the pyomo module
from pyomo.environ import *
from pyomo.opt import SolverFactory
import pyomo.environ

# Creation of a Concrete Model
model = ConcreteModel()

# %%
model.C = Set(initialize=range(Conducteur), doc='les Conducteur')
model.J = Set(initialize=range(len(Adj)), doc='les jobs')
model.A = Set(initialize=range(len(Ex[0])), doc='les arcs')
model.t = Set (initialize=[1,2,4], doc='Terminal')
# %%
model.n = Param(initialize=len(Adj), doc='le nombre de jobs')
model.c = Param(initialize=6, doc='le nombre de conducteur')

model.ex1 = Param(model.A,initialize=Ex[0], doc='extrémité 1')
model.ex2 = Param(model.A,initialize=Ex[1], doc='extrémité 2')
model.T = Param(model.J,initialize=Value_Terminal, doc='les Terminal Affecté')
# %%
model.x = Var(model.C, model.J,domain=Binary, doc='affectation conducteur')
model.alpha = Var(model.C, model.t,domain=Binary, doc='affectation conducteur au terminal')
model.v = Var(model.C,bounds=(0,None),domain=Integers, doc='les taches')
model.y = Var(bounds=(0,None),domain=Integers, doc='valeur de comparaison')

# %%
def Cotraint1(model,j):
  return sum(model.x[i,j] for i in model.C) == 1
model.C1 = Constraint(model.J, rule=Cotraint1, doc='verification daffectation')


def Contraint2(model,i,k):
  return ((model.x[i,model.ex1[k]]+model.x[i,model.ex2[k]])) <= 1  

model.C2 = Constraint (model.C,model.J, rule=Contraint2, doc='verification de non chevauchement ')

def Contraint3(model,i):
  return sum(model.x[i,j] for j in model.J)==model.v[i]

model.C3 = Constraint (model.C, rule=Contraint3, doc='une seul tache par conducteur')

def Contraint4(model,i):
  return (model.v[i]<=model.y)

model.C4 = Constraint (model.C, rule=Contraint4, doc='maximiser')

def Contraint5(model,i):
  return sum(model.alpha[i,k] for k in model.t) == 1
model.C5 = Constraint(model.C, rule=Contraint5, doc='verification daffectation de terminal')

def Contraint6(model,i,j):
  return (model.alpha[i,model.T[j]] >= model.x[i,j] )
model.C6 = Constraint(model.C,model.J, rule=Contraint6, doc='verification daffectation au t')
# %%

# %%
def objective_rule(model):
  return model.y
model.objective = Objective(rule=objective_rule, sense=minimize, doc='Define objective function')

# %%
def pyomo_postprocess(options=None, instance=None, results=None):
  model.x.display()
# %%


opt = SolverFactory("gurobi")
results = opt.solve(model)
#sends results to stdout
results.write()
print("\nDisplaying Solution\n" + '-'*60)
pyomo_postprocess(None, model, results)
# %%




ERROR: Rule failed when generating expression for Constraint C2 with index (0,
    29): KeyError: "Index '29' is not valid for indexed component 'ex1'"
ERROR: Constructing component 'C2' from data=None failed: KeyError: "Index
    '29' is not valid for indexed component 'ex1'"


KeyError: "Index '29' is not valid for indexed component 'ex1'"

In [ ]:
model.v.display()
#verfy how much each driver is working per day

v : les taches
    Size=20, Index=C
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      0 :     0 :  None :  None : False :  True : Integers
      1 :     0 :  None :  None : False :  True : Integers
      2 :     0 :  None :  None : False :  True : Integers
      3 :     0 :  None :  None : False :  True : Integers
      4 :     0 :  None :  None : False :  True : Integers
      5 :     0 :  None :  None : False :  True : Integers
      6 :     0 :  None :  None : False :  True : Integers
      7 :     0 :  None :  None : False :  True : Integers
      8 :     0 :  None :  None : False :  True : Integers
      9 :     0 :  None :  None : False :  True : Integers
     10 :     0 :  None :  None : False :  True : Integers
     11 :     0 :  None :  None : False :  True : Integers
     12 :     0 :  None :  None : False :  True : Integers
     13 :     0 :  None :  None : False :  True : Integers
     14 :     0 :  None :  None : False :  True : Integers
     15 :     0 :  Non

In [ ]:
x=model.x
Group_co=[]
for i in model.C:
    Group_co.append([])
    for j in model.J:
        if x[i,j].value == 1:
            Group_co[i].append(j)

print(Group_co)

Slected_DATETIME= np.array(Selected_Data['DATETIME'])
Slected_Terminal=np.array(Selected_Data['Terminal'])
Slected_PKG=np.array(Selected_Data['PKG'])
#Slected_HPA=np.array(Selected_Data['HPA'])
#Slected_HPD=np.array(Selected_Data['HPD'])
for i in range(len(Group_co)):
    print("list des vols du conducteur "+str(i+1))
    print("Terminal       N Parking          Time")

    for j in Group_co[i]:
        print(Slected_Terminal[j]+'  |  '+Slected_PKG[j]+'  |  '+Slected_DATETIME[j])






[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
list des vols du conducteur 1
Terminal       N Parking          Time
list des vols du conducteur 2
Terminal       N Parking          Time
list des vols du conducteur 3
Terminal       N Parking          Time
list des vols du conducteur 4
Terminal       N Parking          Time
list des vols du conducteur 5
Terminal       N Parking          Time
list des vols du conducteur 6
Terminal       N Parking          Time
list des vols du conducteur 7
Terminal       N Parking          Time
list des vols du conducteur 8
Terminal       N Parking          Time
list des vols du conducteur 9
Terminal       N Parking          Time
list des vols du conducteur 10
Terminal       N Parking          Time
list des vols du conducteur 11
Terminal       N Parking          Time
list des vols du conducteur 12
Terminal       N Parking          Time
list des vols du conducteur 13
Terminal       N Parking          Time
list des vols du c

In [ ]:
Slected_DATETIME= np.array(Selected_Data['DATETIME'])
Slected_Terminal=np.array(Selected_Data['Terminal'])
Slected_PKG=np.array(Selected_Data['PKG'])
Slected_HPA=np.array(Selected_Data['HPA'])
Slected_HPD=np.array(Selected_Data['HPD'])
Slected_date=np.array(Selected_Data['DATE'])

import xlwt
from tempfile import TemporaryFile

import xlwt
from xlwt.Workbook import *
from pandas import ExcelWriter
import xlsxwriter
book = pd.ExcelWriter('Conducteur'+str(Date)+'-'+str(Brigade)+'.xlsx', engine='xlsxwriter')
for i in range(len(Group_co)):
    data=None
    Terminal=[]
    PKG=[]
    date=[]
    HPA=[]
    HPD=[]
    for j in Group_co[i]:
        date.append(Slected_date[j])
        HPA.append(Slected_HPA[j])
        HPD.append(Slected_HPD[j])
        Terminal.append(Slected_Terminal[j])
        PKG.append(Slected_PKG[j])
    
    DATA=list(zip(date, HPA,HPD,Terminal,PKG))
    data=pd.DataFrame(DATA,columns=['date','HPA','HPD','Terminal','PKG'])
    data.to_excel(book, sheet_name='Conducteur '+str(i+1))


In [ ]:
import xlwt
from tempfile import TemporaryFile
book = xlwt.Workbook()
sheet1 = book.add_sheet('sheet1')

supersecretdata = [34,123,4,1234,12,34,12,41,234,123,3,56]

for i,e in enumerate(supersecretdata):
    sheet1.write(i,1,e)

name = "random.xls"
book.save(name)
book.save(TemporaryFile())